CREATE TABLE CATEGORY_PRODUCT (
    ID BIGINT PRIMARY KEY  NOT NULL AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(255),
    CATEGORY_DESCRIPTION VARCHAR(255)
);
CREATE TABLE PRODUCT (
	ID BIGINT PRIMARY KEY  NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    PRICE FLOAT,
    BARCODE VARCHAR(255),
    CATEGORY_ID BIGINT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY_PRODUCT(ID)
);
CREATE TABLE SELLERS (
	ID BIGINT PRIMARY KEY  NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    INTERPRISE_ID VARCHAR(255),
    BIRTH_DATE DATE
);

CREATE TABLE SHOPPING (
	ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CLIENT_NAME VARCHAR(255),
    CLIENT_CPF VARCHAR(255),
    SELLER_ID BIGINT,
    FOREIGN KEY (SELLER_ID) REFERENCES SELLERS(ID)
);

CREATE TABLE PRODUCT_SHOPPING (
	ID BIGINT PRIMARY KEY  NOT NULL AUTO_INCREMENT,
    ID_SHOPPING BIGINT,
    ID_PRODUCT BIGINT,
    QTTD BIGINT,
    FOREIGN KEY (ID_SHOPPING) REFERENCES SHOPPING(ID),
    FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID)
);

